# Generated by Django 6.0.7 on 2026-08-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_statusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
